import { Module } from '@nestjs/common';
import { PeopleService } from './people.service';
import { 
  PeopleController, 
  DepartmentsController, 
  AttendanceController,
  AttendanceSummaryController,
  AttendancePolicyController,
  LeaveTypesController,
  LeaveRequestsController,
  LeaveBalancesController,
  LeaveApprovalsController,
  LeavePoliciesController,
  HolidaysController,
  LeaveAccrualsController,
  PayrollRecordsController,
  PayrollConfigurationsController,
  PayrollExceptionsController,
  CustomPayrollComponentsController,
  PerformanceReviewsController,
  PerformanceGoalsController,
  ReviewCyclesController,
  ReviewTemplatesController,
  GoalsController,
  SkillsController,
  EmployeeSkillsController,
  CompetenciesController,
  CompetencyAssessmentsController,
  CoursesController,
  CourseEnrollmentsController,
  LearningPathsController,
  CertificationsController,
  EmployeeCertificationsController,
  CareerPathsController,
  CareerPathEnrollmentsController,
  AnnouncementsController,
  MessagesController,
  JobPostingsController,
  ApplicantsController,
  OnboardingPlansController,
  OnboardingTasksController,
  AuthController,
  UsersController,
  HierarchyController,
  ApprovalsController,
  NotificationsController,
  AuditLogsController,
} from './people.controller';
import { ClientsModule, Transport } from '@nestjs/microservices';
import { join } from 'path';
import { AuthModule } from '../auth/auth.module';
import { AccountsModule } from '../accounts/accounts.module';

@Module({
  imports: [
    AuthModule, // Import AuthModule to use JwtAuthGuard
    AccountsModule, // Auth routes delegate to Accounts
    ClientsModule.register([
      {
        name: 'PEOPLE_PACKAGE',
        transport: Transport.GRPC,
        options: {
          package: 'people',
          url: process.env.PEOPLE_GRPC_URL || 'people:50056',
          protoPath: join(process.cwd(), 'proto/people/people.proto'),
        },
      },
    ]),
  ],
  controllers: [
    PeopleController, 
    DepartmentsController,
    AttendanceController,
    AttendanceSummaryController,
    AttendancePolicyController,
    LeaveTypesController,
    LeaveRequestsController,
    LeaveBalancesController,
    LeaveApprovalsController,
    LeavePoliciesController,
    HolidaysController,
    LeaveAccrualsController,
    PayrollRecordsController,
    PayrollConfigurationsController,
    PayrollExceptionsController,
    CustomPayrollComponentsController,
    PerformanceReviewsController,
    PerformanceGoalsController,
    ReviewCyclesController,
    ReviewTemplatesController,
    GoalsController,
    SkillsController,
    EmployeeSkillsController,
    CompetenciesController,
    CompetencyAssessmentsController,
    CoursesController,
    CourseEnrollmentsController,
    LearningPathsController,
    CertificationsController,
    EmployeeCertificationsController,
    CareerPathsController,
    CareerPathEnrollmentsController,
    AnnouncementsController,
    MessagesController,
    JobPostingsController,
    ApplicantsController,
    OnboardingPlansController,
    OnboardingTasksController,
    AuthController,
    UsersController,
    HierarchyController,
    ApprovalsController,
    NotificationsController,
    AuditLogsController,
  ],
  providers: [PeopleService],
})
export class PeopleModule {}

